### ISSUE TITLE
No module named 'modules.senet'

### ISSUE THREAD

**Issue by drickzsy** [bupt-ai-cz/Meta-SelfLearning#2]
Hello, thank you for your open code.
May I have a question about No module named 'modules.senet' in feature_extraction.py line 3? 
Hope for your reply!

**Comment by NarcissusInMirror** [comment]
Hi there, you can just comment this line in `feature_extraction.py`. It was added for another experiment, and I forgot to delete it before uploading the file. I've deleted related lines in the new version, thank you for your reminder.
