### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by VixeruntR** [bupt-ai-cz/Meta-SelfLearning#3]
作者您好，请问可以提供预训练模型吗？

**Comment by NarcissusInMirror** [comment]
您好，预训练模型已经上传至百度网盘，欢迎下载
链接:https://pan.baidu.com/s/1YWeWfSRfpDMkFdIatX_eRQ  密码:x5v7

**Comment by VixeruntR** [comment]
> x5v7

非常感谢！

**Comment by VixeruntR** [comment]
> 您好，预训练模型已经上传至百度网盘，欢迎下载 链接:https://pan.baidu.com/s/1YWeWfSRfpDMkFdIatX_eRQ 密码:x5v7

非常感谢！
